### ISSUE TITLE
Port of SpenDB API

### ISSUE THREAD

**Issue by pwalsh** [openspending/os-api#1]
# Description

We are integrating SpenDB work into OpenSpending Next. Our API is based on Babbage, using a customer loader from Fiscal Data Package to Babbage. Babbage includes a Flask blueprint to expose an HTTP API. SpenDB uses Babbage and does extra stuff to create (some) API endpoints that are compatible with the old version of OpenSpending.

So, in the new OpenSpending API, ensure that we've brought over all customisations that SpenDB does to default Babbage. 

We start from a new codebase rather than forking SpenDB as SpenDB has various things that are not relevant to our API (separation of concerns via components/services in OpenSpending Next).

# Tasks

* [x] Customize/extend/refactor our base Babbage API endpoints with any additions from SpenDB
* [x] Good test coverage (Py2/3)

**Comment by akariv** [comment]
@pwalsh which APIs from the current OS do we want to clone for backward compatibility)?
Currently there are 5 (according to the docs): aggregate, rest, mytax, search and loading.
- I'm guessing aggregate is for sure.
- Probably search as well
- not sure about rest
- mytax and loading probably not

**Comment by pudo** [comment]
@akariv Search was full-text across all available datasets. This is cool for finding e.g. supplier names, but it cries "stand-alone service" to me. "Rest" was everything but actually RESTful. Virtually all visualisations would just need aggregate, so that should actually work OK. 

mytax already exists as a service, see openspending/taxman

**Comment by akariv** [comment]
@pudo Thanks! so the real question I think is whether someone is actually using these old APIs or can we just take them down without any impact on anyone.

**Comment by pwalsh** [comment]
@akariv 

ah.. @pudo beat me to it.

Search should be standalone. Just the aggregate and "REST", I'd say.

**Comment by pudo** [comment]
Taking away ``/api/2/aggregate`` would piss people off. So I'd also make this a thin wrapper on babbage, it's really just a subset.

**Comment by akariv** [comment]
@pudo sure - I meant the _other_ old APIs :) (search et al)

**Comment by pwalsh** [comment]
DONE
